import { QRStyleConfig, StylePreset, StylePresetKey } from '../types';

export const DEFAULT_STYLE: QRStyleConfig = {
  fgColor: '#00f2fe',
  bgColor: '#0b0f19',
  dotType: 'rounded',
  cornerSquareType: 'extra-rounded',
  cornerDotType: 'dot',
  errorCorrection: 'Q',
  margin: 16,
  size: 320,
  logoUrl: undefined,
  logoSize: 0.22,
};

export const STYLE_PRESETS: Record<StylePresetKey, StylePreset> = {
  midnight: {
    id: 'midnight',
    name: 'Midnight',
    description: 'Cyberpunk neon cyan on deep obsidian',
    fgColor: '#00f2fe',
    bgColor: '#0b0f19',
    dotType: 'rounded',
    cornerSquareType: 'extra-rounded',
    cornerDotType: 'dot',
    previewClass: 'from-cyan-500 to-slate-950',
  },
  neon: {
    id: 'neon',
    name: 'Neon Nova',
    description: 'Electric lime & emerald glow',
    fgColor: '#10b981',
    bgColor: '#04100c',
    dotType: 'dots',
    cornerSquareType: 'extra-rounded',
    cornerDotType: 'dot',
    previewClass: 'from-emerald-400 to-teal-950',
  },
  classic: {
    id: 'classic',
    name: 'Classic',
    description: 'High-contrast standard monochrome',
    fgColor: '#000000',
    bgColor: '#ffffff',
    dotType: 'square',
    cornerSquareType: 'square',
    cornerDotType: 'square',
    previewClass: 'from-gray-900 to-white',
  },
  ocean: {
    id: 'ocean',
    name: 'Ocean Wave',
    description: 'Deep cobalt on crisp ice blue',
    fgColor: '#0284c7',
    bgColor: '#f0f9ff',
    dotType: 'classy-rounded',
    cornerSquareType: 'extra-rounded',
    cornerDotType: 'dot',
    previewClass: 'from-blue-600 to-sky-100',
  },
  sunset: {
    id: 'sunset',
    name: 'Sunset Glow',
    description: 'Warm coral red on twilight slate',
    fgColor: '#f43f5e',
    bgColor: '#181119',
    dotType: 'rounded',
    cornerSquareType: 'extra-rounded',
    cornerDotType: 'dot',
    previewClass: 'from-rose-500 to-amber-950',
  },
  minimal: {
    id: 'minimal',
    name: 'Minimal Pure',
    description: 'Modern muted graphite on white',
    fgColor: '#334155',
    bgColor: '#f8fafc',
    dotType: 'classy',
    cornerSquareType: 'extra-rounded',
    cornerDotType: 'dot',
    previewClass: 'from-slate-700 to-slate-100',
  },
};
